// Canonical top-level test-contract entry. Keep nested ticker-knowledge contracts
// behind this manifest-owned file so tests/test-contracts.json stays stable.
import "./ai-council-research-context.base.ts"
import "./ticker-knowledge/notion-sync.test.ts"
import "./ticker-knowledge/context.test.ts"
import "./ticker-knowledge/council-degraded.test.ts"
import "./ticker-knowledge/production-readiness.test.ts"
import "./ticker-knowledge/production-backfill.test.ts"
import "./ticker-knowledge/production-acceptance-api.test.ts"
import "./ticker-knowledge/production-evaluation.test.ts"
import "./ticker-qa/service.test.ts"
import "./ticker-qa/schema.test.ts"
import "./ticker-qa/openai.test.ts"
import "./ticker-qa/orchestration.test.ts"
import "./ticker-qa/api.test.ts"
import "./ticker-qa/canonical-id.test.ts"
import "./ticker-qa/canonical-budget.test.ts"
import "./ticker-qa/canonical-council-schema.test.ts"
