import assert from "node:assert/strict"
import { existsSync, readFileSync, readdirSync } from "node:fs"
import test from "node:test"

import {
  QEO232_DAILY_PROVENANCE_READERS,
  QEO232_DAILY_PROVENANCE_WRITERS,
  assertQeo232DailyProvenanceSchema,
} from "./helpers/qeo-232-daily-provenance-schema-contract.ts"

function source(path: string) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8")
}

const SAFE_ADDITIVE_SQL = `
begin;
create table public.market_ohlcv_provenance (
  id bigint generated by default as identity primary key,
  identity_version smallint not null default 1,
  provider text not null,
  provider_detail text not null,
  source_url text not null,
  created_at timestamptz not null default now(),
  unique (identity_version, provider, provider_detail, source_url),
  check (identity_version = 1)
);
alter table public.market_ohlcv_history
  add column provenance_id bigint null;
alter table public.market_ohlcv_history
  add constraint market_ohlcv_history_provenance_id_fkey
  foreign key (provenance_id)
  references public.market_ohlcv_provenance(id)
  on delete restrict;
create or replace function public.qeo_market_ohlcv_recent_grouped(
  p_tickers text[],
  p_limit integer default 260
)
returns table (ticker text, rows jsonb)
language sql
stable
as $$
  select q.ticker,
    jsonb_agg(jsonb_build_array(
      h.bar_time, h.open, h.high, h.low, h.close, h.volume,
      h.provider, h.provider_detail, h.source_url, h.fetched_at
    ) order by h.bar_time)
  from requested q
  join hydrated_daily_compat h on h.ticker = q.ticker
  group by q.ticker;
$$;
commit;
`

test("QEO-232 accepts the approved additive Daily provenance shape", () => {
  assert.doesNotThrow(() => assertQeo232DailyProvenanceSchema(SAFE_ADDITIVE_SQL))
})

test("QEO-232 rejects schema changes that violate additive/rollback safety", () => {
  const unsafe = [
    SAFE_ADDITIVE_SQL.replace("identity_version smallint not null default 1", "identity_version smallint"),
    SAFE_ADDITIVE_SQL.replace(
      "unique (identity_version, provider, provider_detail, source_url)",
      "unique (source_url)",
    ),
    SAFE_ADDITIVE_SQL.replace("provenance_id bigint null", "provenance_id bigint not null"),
    SAFE_ADDITIVE_SQL.replace("on delete restrict", "on delete cascade"),
    `${SAFE_ADDITIVE_SQL}\nalter table public.market_ohlcv_history drop column provider_detail;`,
    `${SAFE_ADDITIVE_SQL}\nalter table public.market_ohlcv_history drop column source_url;`,
    `${SAFE_ADDITIVE_SQL}\nselect * from public.chart_ohlcv_provenance_batches;`,
    `${SAFE_ADDITIVE_SQL}\nvacuum full public.market_ohlcv_history;`,
    `${SAFE_ADDITIVE_SQL}\ndelete from public.market_ohlcv_history;`,
    `${SAFE_ADDITIVE_SQL}\ncreate table public.market_ohlcv_history_shadow as select * from public.market_ohlcv_history;`,
  ]

  for (const sql of unsafe) {
    assert.throws(() => assertQeo232DailyProvenanceSchema(sql))
  }
})

test("QEO-232 locks the current grouped Daily width-10 ABI", () => {
  const decoder = source("modules/market/history/ohlcv-grouped.ts")
  assert.match(decoder, /COMPACT_DAILY_ROW_WIDTH\s*=\s*10/)
  assert.match(
    decoder,
    /\[barTime, open, high, low, close, volume, provider, providerDetail, sourceUrl, fetchedAt\]/,
  )

  const groupedRpc = source("supabase/migrations/20260902205000_qeo39_grouped_ohlcv_rpc.sql")
  assert.match(
    groupedRpc,
    /jsonb_build_array\([\s\S]*?h\.bar_time,[\s\S]*?h\.open,[\s\S]*?h\.high,[\s\S]*?h\.low,[\s\S]*?h\.close,[\s\S]*?h\.volume,[\s\S]*?h\.provider,[\s\S]*?h\.provider_detail,[\s\S]*?h\.source_url,[\s\S]*?h\.fetched_at[\s\S]*?\)/,
  )
})

test("QEO-232 keeps the approved writer and provenance-sensitive reader inventory explicit", () => {
  assert.deepEqual(QEO232_DAILY_PROVENANCE_WRITERS, [
    "modules/market/history/ohlcv-store.ts",
    "modules/market/history/daily-integrity.ts",
    "modules/eod/no-trade-repair-step.ts",
  ])

  assert.deepEqual(QEO232_DAILY_PROVENANCE_READERS, [
    "modules/market/history/ohlcv-store.ts",
    "modules/market/history/daily-integrity.ts",
    "modules/market/chart-data/daily-authority.ts",
    "modules/market/chart-data/service.ts",
    "modules/market/chart-data/maintenance.ts",
    "modules/market/history/daily-cold-history.ts",
    "modules/market/history/ohlcv-grouped.ts",
    "modules/wyckoff/eod-ingest.ts",
  ])

  for (const path of [...QEO232_DAILY_PROVENANCE_WRITERS, ...QEO232_DAILY_PROVENANCE_READERS]) {
    assert.equal(existsSync(new URL(`../${path}`, import.meta.url)), true, `missing inventoried path: ${path}`)
  }

  for (const path of QEO232_DAILY_PROVENANCE_WRITERS) {
    const text = source(path)
    assert.match(text, /provider/)
    assert.match(text, /provider_detail/)
    assert.match(text, /source_url/)
    assert.match(text, /fetched_at/)
  }
})

test("QEO-232 automatically validates future QEO-233 provenance migrations when they appear", () => {
  const migrationDir = new URL("../supabase/migrations/", import.meta.url)
  const matches = readdirSync(migrationDir)
    .filter((name) => /_qeo233_daily_ohlcv_provenance.*\.sql$/.test(name))
    .sort()

  if (matches.length === 0) return
  const combined = matches.map((name) => source(`supabase/migrations/${name}`)).join("\n")
  assertQeo232DailyProvenanceSchema(combined)
})
