import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const dashboard = readFileSync("components/insights/wyckoff-chart-dashboard.tsx", "utf8")
const chart = readFileSync("components/insights/wyckoff-lightweight-chart.tsx", "utf8")
const chartRuntime = readFileSync("lib/lightweight-charts-runtime.ts", "utf8")
const stockIdentity = readFileSync("components/stock-identity.tsx", "utf8")
const insightsDashboard = readFileSync("components/insights/insights-dashboard.tsx", "utf8")
const orderbook = readFileSync("components/orderbook/live-orderbook-panel.tsx", "utf8")
const page = readFileSync("app/insights/wyckoff/page.tsx", "utf8")
const tickerApi = readFileSync("app/api/insights/wyckoff/route.ts", "utf8")
const unifiedData = readFileSync("lib/wyckoff-unified-data.ts", "utf8")
const metadata = readFileSync("lib/wyckoff-company-metadata.ts", "utf8")
const animatedTabs = readFileSync("components/smoothui/animated-tabs/index.tsx", "utf8")
const aiLoader = readFileSync("components/smoothui/ai-loader/index.tsx", "utf8")
const priceFlow = readFileSync("components/smoothui/price-flow/index.tsx", "utf8")
const marketSectors = readFileSync("lib/market-sectors.ts", "utf8")

test("Wyckoff header uses the canonical stock identity and removes the Rating back row", () => {
  assert.match(dashboard, /companyName\?: string/)
  assert.match(dashboard, /import \{ StockIdentity \}/)
  assert.match(dashboard, /<StockIdentity[\s\S]*ticker=\{ticker\}/)
  assert.doesNotMatch(dashboard, /function SymbolIdentity/)
  assert.doesNotMatch(dashboard, /data-wyckoff-back-row|Quay lại Rating|>\s*Rating\s*</)
  assert.doesNotMatch(dashboard, /ArrowLeft/)
})

test("stock identity convention matches stock detail and orderbook popup styling", () => {
  const tickerGradient = "bg-gradient-to-br from-white via-cyan-100 to-emerald-200 bg-clip-text text-transparent"
  const logoGlow = "drop-shadow-[0_0_8px_rgba(255,255,255,0.75)]"
  const tickerGlow = "drop-shadow-[0_0_15px_rgba(34,211,238,0.2)]"

  assert.match(stockIdentity, /export const STOCK_IDENTITY_LOGO_CLASS/)
  assert.match(stockIdentity, /export const STOCK_IDENTITY_TICKER_CLASS/)
  assert.ok(stockIdentity.includes(tickerGradient))
  assert.ok(stockIdentity.includes(logoGlow))
  assert.ok(stockIdentity.includes(tickerGlow))
  assert.ok(insightsDashboard.includes(tickerGradient))
  assert.ok(insightsDashboard.includes(logoGlow))
  assert.ok(insightsDashboard.includes(tickerGlow))
  assert.ok(orderbook.includes(tickerGradient))
  assert.ok(orderbook.includes(logoGlow))
  assert.ok(orderbook.includes(tickerGlow))
})

test("Wyckoff watchlist stays ticker-first and groups rows by the market-board sector taxonomy", () => {
  const rowStart = dashboard.indexOf("const WatchlistRow")
  const rowEnd = dashboard.indexOf("export function WyckoffStockWorkspace", rowStart)
  const rowSource = dashboard.slice(rowStart, rowEnd)

  assert.match(dashboard, /BOARD_SECTOR_GROUPS/)
  assert.match(dashboard, /boardSectorGroupForSector/)
  assert.match(dashboard, /groupedStocks\.map/)
  assert.match(marketSectors, /BOARD_SECTOR_GROUPS/)
  assert.match(marketSectors, /key: "bank"/)
  assert.match(marketSectors, /key: "securities"/)
  assert.match(marketSectors, /key: "consumer"/)
  assert.match(marketSectors, /key: "real-estate"/)
  assert.match(marketSectors, /key: "industrial-tech"/)
  assert.match(marketSectors, /key: "other"/)
  assert.match(dashboard, />Mã<\/div>/)
  assert.match(dashboard, /placeholder="Tìm mã\.\.\."/)
  assert.match(rowSource, /text-\[15px\]/)
  assert.match(rowSource, /content-visibility:auto/)
  assert.match(rowSource, /<a[\s\S]*href=\{href\}/)
  assert.doesNotMatch(rowSource, /companyName|exchange|stock\.sector|StockLogo/)
  assert.doesNotMatch(rowSource, /<Link|prefetch=/)
})

test("Wyckoff phase column uses compact badges that cannot overlap price-change text", () => {
  const rowStart = dashboard.indexOf("const WatchlistRow")
  const rowEnd = dashboard.indexOf("export function WyckoffStockWorkspace", rowStart)
  const rowSource = dashboard.slice(rowStart, rowEnd)

  assert.match(dashboard, /WATCHLIST_GRID_CLASS = "grid-cols-\[64px_74px_64px_minmax\(0,1fr\)\]"/)
  assert.match(dashboard, /function phaseCompactLabel/)
  assert.match(dashboard, /return "RE-ACC"/)
  assert.match(dashboard, /return "RE-DIST"/)
  assert.match(dashboard, /return "MARKUP"/)
  assert.match(dashboard, /return "MARKDOWN"/)
  assert.match(rowSource, /overflow-hidden text-ellipsis whitespace-nowrap/)
  assert.match(rowSource, /title=\{fullPhase\}/)
  assert.match(rowSource, /phaseCompactLabel\(stock\.phase\)/)
  assert.doesNotMatch(rowSource, /grid-cols-\[minmax\(70px,1fr\)_76px_72px_88px\]/)
})

test("Wyckoff ticker switching remains cancellable and latest-click-wins", () => {
  assert.match(dashboard, /TICKER_SWITCH_DEBOUNCE_MS = 60/)
  assert.match(dashboard, /new AbortController\(\)/)
  assert.match(dashboard, /switchAbortRef\.current\?\.abort\(\)/)
  assert.match(dashboard, /switchSequenceRef\.current/)
  assert.match(dashboard, /sequence !== switchSequenceRef\.current/)
  assert.match(dashboard, /fetch\(`\/api\/insights\/wyckoff\?ticker=/)
  assert.match(dashboard, /window\.history\.replaceState\(window\.history\.state, "", url\)/)
  assert.match(dashboard, /startTransition\(\(\) => setTickerData\(nextData\)\)/)
  assert.match(dashboard, /TICKER_CACHE_LIMIT = 8/)
  assert.match(dashboard, /onSelectTicker=\{selectTicker\}/)
  assert.doesNotMatch(dashboard, /router\.refresh\(\)|window\.history\.pushState|useRouter/)
})

test("Wyckoff ticker endpoint is authenticated and reads only the selected ticker payload", () => {
  assert.match(tickerApi, /requireApiUser/)
  assert.match(tickerApi, /getUnifiedWyckoffTickerData/)
  assert.match(tickerApi, /Cache-Control/)
  assert.match(unifiedData, /export async function getUnifiedWyckoffTickerData/)
  const selectedStart = unifiedData.indexOf("export async function getUnifiedWyckoffTickerData")
  const selectedSource = unifiedData.slice(selectedStart)
  assert.match(selectedSource, /\.eq\("ticker", ticker\)/)
  assert.match(selectedSource, /getWyckoffCompanyMetadata\(supabase, \[ticker\]\)/)
  assert.doesNotMatch(selectedSource, /\.in\("ticker", tickers\)/)
})

test("Wyckoff timeframe keeps bounded SmoothUI AnimatedTabs inside the chart toolbar", () => {
  assert.match(dashboard, /import \{ AnimatedTabs \}/)
  assert.match(dashboard, /data-wyckoff-chart-toolbar/)
  assert.match(dashboard, /<AnimatedTabs[\s\S]*ariaLabel="Khung thời gian biểu đồ"/)
  assert.match(animatedTabs, /layoutId=/)
  assert.match(animatedTabs, /useReducedMotion/)
  assert.doesNotMatch(animatedTabs, /transition-all|backdrop-blur|backdrop-filter|filter:/)
})

test("chart loading is visual-only inside chart content and compositor-safe", () => {
  assert.match(chart, /loading = false/)
  assert.match(chart, /<AiLoader/)
  assert.match(chart, /showLabel=\{false\}/)
  assert.match(chart, /compositorSafe/)
  assert.match(chart, /h-\[520px\]/)
  assert.match(chart, /xl:h-\[660px\]/)
  assert.match(chart, /\[contain:layout_paint\]/)
  assert.match(aiLoader, /showLabel = true/)
  assert.match(aiLoader, /compositorSafe = false/)
  assert.match(aiLoader, /opacity: \[0\.25, 1, 0\.25\]/)
  assert.doesNotMatch(dashboard, /Đang tải \{pendingTicker\}/)
  assert.doesNotMatch(aiLoader, /backdrop-blur|backdrop-filter|filter:/)
})

test("Price Flow is suppressed during ticker commits to avoid simultaneous compositor work", () => {
  assert.match(dashboard, /suppressValueMotion/)
  assert.match(dashboard, /setSuppressValueMotion\(true\)/)
  assert.match(dashboard, /const priceMotion = !suppressValueMotion/)
  assert.match(dashboard, /animate=\{priceMotion\}/)
  assert.match(priceFlow, /animate = true/)
  assert.match(priceFlow, /const shouldAnimate = animate && !reducedMotion/)

  const rowStart = dashboard.indexOf("const WatchlistRow")
  const rowEnd = dashboard.indexOf("export function WyckoffStockWorkspace", rowStart)
  assert.doesNotMatch(dashboard.slice(rowStart, rowEnd), /PriceFlow/)
})

test("Wyckoff chart keeps one persistent canvas surface and updates series in place", () => {
  assert.match(chart, /controllerRef/)
  assert.match(chart, /function applyStudy/)
  assert.match(chart, /controller\.candles\.setData/)
  assert.match(chart, /controller\.volume\.setData/)
  assert.match(chart, /controller\.markers\?\.setMarkers/)
  assert.match(chart, /series\.applyOptions/)
  assert.match(chart, /series\.setData/)
  assert.match(chart, /removePriceLine/)
  assert.match(chart, /\}, \[\]\)/)
  assert.doesNotMatch(chart, /activeSlotRef|pendingSlotRef|visibility = "hidden"|nextPaint|removeSlot/)
  assert.doesNotMatch(chart, /document\.createElement\("div"\)/)
})

test("Wyckoff chart uses raster-safe visual primitives on scaled 4K displays", () => {
  assert.match(chart, /vertLines:\s*\{\s*visible:\s*false\s*\}/)
  assert.match(chart, /horzLines:\s*\{\s*visible:\s*false\s*\}/)
  assert.match(chart, /study\.analysis\.support\)\.slice\(0, 1\)/)
  assert.match(chart, /study\.analysis\.resistance\)\.slice\(0, 1\)/)
  assert.match(chart, /lineWidth:\s*2/)
  assert.match(chart, /lineStyle:\s*0/)
  assert.match(chart, /priceLineVisible:\s*false/)
  assert.doesNotMatch(chart, /lineStyle:\s*2/)
  assert.doesNotMatch(chart, /vertLines:\s*\{\s*color:/)
  assert.doesNotMatch(chart, /horzLines:\s*\{\s*color:/)
})

test("Wyckoff chart caps the physical raster viewport before large-window flicker threshold", () => {
  assert.match(chart, /data-wyckoff-chart-raster-viewport/)
  assert.match(chart, /max-w-\[1360px\]/)
  assert.match(chart, /\[contain:paint\]/)
  assert.match(chart, /setHeight\(84\)/)
  assert.match(chart, /wickUpColor:\s*"rgba\(34,201,138,0\.68\)"/)
  assert.match(chart, /wickDownColor:\s*"rgba\(255,71,87,0\.68\)"/)
  assert.match(chart, /rgba\(34,201,138,0\.28\)/)
  assert.match(chart, /rgba\(255,71,87,0\.28\)/)
})

test("Wyckoff chart disables every zoom path while preserving drag panning", () => {
  assert.match(chart, /handleScroll:\s*\{[\s\S]*mouseWheel:\s*false[\s\S]*pressedMouseMove:\s*true/)
  assert.match(chart, /handleScale:\s*false/)
  assert.doesNotMatch(chart, /ZOOM_SETTLE_MS|ZOOM_STEP|MIN_VISIBLE_BARS/)
  assert.doesNotMatch(chart, /applyDiscreteZoom|pendingWheelDelta|pendingAnchorRatio/)
  assert.doesNotMatch(chart, /addEventListener\("wheel"|removeEventListener\("wheel"/)
  assert.doesNotMatch(chart, /subscribeVisibleLogicalRangeChange|unsubscribeVisibleLogicalRangeChange/)
  assert.doesNotMatch(chart, /pinch:\s*true|pinch:\s*embedded/)
})

test("Wyckoff chart resize remains rAF-batched without autoSize or full-surface swapping", () => {
  assert.doesNotMatch(page, /<WyckoffChartDashboard\s+key=|key=\{ticker\}|key=\{unified\.ticker\}/)
  assert.match(chart, /new ResizeObserver/)
  assert.match(chart, /requestAnimationFrame/)
  assert.match(chart, /currentChart\.applyOptions/)
  assert.doesNotMatch(chart, /autoSize:\s*true/)
  assert.match(chartRuntime, /applyOptions\(options: Record<string, unknown>\)/)
  assert.match(chartRuntime, /removePriceLine\?/)
})

test("Wyckoff dashboard avoids large ticker-switch motion ancestors", () => {
  assert.doesNotMatch(dashboard, /LazyMotion|AnimatePresence|motion\/react/)
  assert.doesNotMatch(dashboard, /transition-all|backdrop-blur|backdrop-filter|drop-shadow/)
  assert.doesNotMatch(dashboard, /filter:\s*/)
  assert.match(dashboard, /<WyckoffLightweightChart ticker=\{ticker\} study=\{current\} loading=\{isLoading\}/)
})

test("company metadata is selected-ticker only and remains fail-open", () => {
  assert.match(metadata, /select\("as_of_date"\)/)
  assert.match(metadata, /select\("ticker,company_name,sector,exchange"\)/)
  assert.match(metadata, /\.eq\("is_published", true\)/)
  assert.match(metadata, /return new Map\(\)/)
  assert.match(unifiedData, /getWyckoffCompanyMetadata\(supabase, \[ticker\]\)/)
  assert.match(page, /getWyckoffCompanyMetadata\(auth\.supabase, \[ticker\]\)/)
  assert.doesNotMatch(unifiedData, /getWyckoffCompanyMetadata\(supabase, tickers\)/)
})
