import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const page = readFileSync("app/insights/wyckoff/page.tsx", "utf8")
const infographic = readFileSync("components/insights/wyckoff-infographic-dashboard.tsx", "utf8")
const chart = readFileSync("components/insights/wyckoff-lightweight-chart.tsx", "utf8")
const unified = readFileSync("lib/wyckoff-unified-data.ts", "utf8")

test("standalone Wyckoff page routes to the infographic dashboard", () => {
  assert.match(page, /WyckoffInfographicDashboard/)
  assert.match(page, /dataSource="Supabase unified"/)
  assert.doesNotMatch(page, /return <WyckoffChartDashboard/)
})

test("Wyckoff structure lab uses Plus Jakarta and shadcn primitives", () => {
  assert.match(infographic, /font-ticker/)
  assert.match(infographic, /const TYPE =/)
  assert.match(infographic, /display:/)
  assert.match(infographic, /section:/)
  assert.match(infographic, /value:/)
  assert.match(infographic, /body:/)
  assert.match(infographic, /meta:/)
  assert.match(infographic, /@\/components\/ui\/card/)
  assert.match(infographic, /@\/components\/ui\/badge/)
  assert.match(infographic, /@\/components\/ui\/button/)
  assert.match(infographic, /@\/components\/ui\/input/)
  assert.match(infographic, /@\/components\/ui\/tooltip/)
  assert.doesNotMatch(infographic, /font-mono/)
  assert.doesNotMatch(infographic, /text-\[(?:9|10|11)px\]/)
  assert.match(chart, /--font-plus-jakarta-sans/)
})

test("standalone Wyckoff keeps only structure, levels, events and price-volume evidence", () => {
  assert.match(infographic, /Cấu trúc Wyckoff hiện tại/)
  assert.match(infographic, /Key Wyckoff levels/)
  assert.match(infographic, /Wyckoff Events/)
  assert.match(infographic, /Price × Volume × Wyckoff Events/)
  assert.match(infographic, /Breakout → Hold → Retest → Follow-through/)
  assert.match(infographic, /RelVol/)
  assert.match(infographic, /showIntelligence=\{false\}/)
  assert.match(infographic, /showScenarios=\{false\}/)
  assert.doesNotMatch(infographic, /RSI 14|MA20|MA50|MA200/)
  assert.doesNotMatch(infographic, /ProbabilityBar|Bull \{|Base \{|Bear \{|Conditional target|Kịch bản theo thời gian|OutlookBoard/)
})

test("Wyckoff terminology stays English while explanations stay plain Vietnamese", () => {
  assert.match(infographic, /name: "Spring"/)
  assert.match(infographic, /name: "SOS — Sign of Strength"/)
  assert.match(infographic, /name: "UT \/ UTAD"/)
  assert.match(infographic, /name: "SOW — Sign of Weakness"/)
  assert.match(infographic, /Trading Range/)
  assert.match(infographic, /Support/)
  assert.match(infographic, /Resistance/)
  assert.match(infographic, /Demand/)
  assert.match(infographic, /Supply/)
  assert.match(infographic, /Nhìn tiếp:/)
  assert.match(infographic, /Khi nào coi như sai/)
  assert.doesNotMatch(infographic, /replace\(\/trading range\/gi/)
  assert.doesNotMatch(infographic, /replace\(\/\\bdemand\\b\/gi/)
})

test("multi-timeframe module replaces forecast cards with Wyckoff structure alignment", () => {
  assert.match(infographic, /Multi-timeframe Wyckoff structure/)
  assert.match(infographic, /ưu tiên 1D và 1W hơn 1H/)
  assert.match(infographic, /rangePosition\(study\)/)
  assert.match(infographic, /latestStudyEvent\(study\)/)
  assert.doesNotMatch(infographic, /outlooks\.map|dominantScenario|probabilitySegments/)
})

test("Wyckoff watchlist shows phase chips, explanations, vertical dividers and 1H 1D 1W columns", () => {
  assert.match(infographic, /WATCHLIST_GRID_CLASS = "grid-cols-\[64px_repeat\(3,minmax\(0,1fr\)\)\]"/)
  assert.match(infographic, /1H · 1D · 1W Phase overview/)
  assert.match(infographic, /const PHASE_META:/)
  assert.match(infographic, /label: "Accumulation"/)
  assert.match(infographic, /label: "Reaccumulation"/)
  assert.match(infographic, /label: "Distribution"/)
  assert.match(infographic, /label: "Redistribution"/)
  assert.match(infographic, /label: "Markup"/)
  assert.match(infographic, /label: "Markdown"/)
  assert.match(infographic, /label: "Unclassified"/)
  assert.match(infographic, /function PhaseChip/)
  assert.match(infographic, /function WatchlistExplainPanel/)
  assert.match(infographic, /TooltipContent/)
  assert.match(infographic, /border-l border-white\/\[0\.065\]/)
  assert.match(infographic, /1D Accumulation/)
  assert.match(infographic, /1D Distribution/)
  assert.match(infographic, /placeholder="Tìm mã hoặc Phase\.\.\."/)
  assert.match(infographic, /phaseFor\(stock, "1H"\)/)
  assert.match(infographic, /phaseFor\(stock, "1D"\)/)
  assert.match(infographic, /phaseFor\(stock, "1W"\)/)
  assert.doesNotMatch(infographic, />Event<\/div>/)
  assert.doesNotMatch(infographic, /Mã · Phase · Event/)
  assert.match(unified, /\.in\("timeframe", \["1H", "1D", "1W"\]\)/)
  assert.match(unified, /phase1H: row1H\?\.phase/)
  assert.match(unified, /phase1D: row1D\?\.phase/)
  assert.match(unified, /phase1W: row1W\?\.phase/)
})

test("watchlist restores lightweight pre-redesign transition language without chart motion ancestors", () => {
  assert.match(infographic, /transition-\[background-color,border-color,transform\] duration-200 ease-out/)
  assert.match(infographic, /hover:-translate-y-px/)
  assert.match(infographic, /animate-in fade-in-0 slide-in-from-top-1 duration-200/)
  assert.match(infographic, /active:scale-\[0\.98\]/)
  assert.doesNotMatch(infographic, /LazyMotion|AnimatePresence|motion\/react/)
  assert.doesNotMatch(infographic, /backdrop-blur|backdrop-filter/)
})

test("structure-only mode keeps the existing persistent lightweight chart surface", () => {
  assert.match(infographic, /<WyckoffLightweightChart/)
  assert.match(chart, /showScenarios = true/)
  assert.match(chart, /if \(showScenarios\)/)
  assert.doesNotMatch(infographic, /LazyMotion|AnimatePresence|motion\/react/)
  assert.doesNotMatch(infographic, /backdrop-blur|backdrop-filter/)
})
