import Link from "next/link"
import { Activity, ChartNoAxesCombined, Clock3, ShieldAlert, Target, Trophy } from "lucide-react"
import { TickerResearchLink } from "@/components/ticker-research-link"
import { TopNav } from "@/components/top-nav"
import type { SignalEventRow, TradeRecommendation } from "@/lib/signal-data"
import type { RecommendationPerformance } from "@/lib/signal-performance"

function pct(value: number | null | undefined) { return value == null || !Number.isFinite(value) ? "—" : `${value >= 0 ? "+" : ""}${value.toFixed(2)}%` }
function num(value: number | null | undefined) { return value == null || !Number.isFinite(value) ? "—" : value.toLocaleString("en-US", { maximumFractionDigits: 2 }) }
function time(value: string) { if (!value) return "—"; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : new Intl.DateTimeFormat("vi-VN", { timeZone: "Asia/Ho_Chi_Minh", day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).format(d) }
function dateKey(value: string) { if (!value) return ""; const d = new Date(value); return Number.isNaN(d.getTime()) ? "" : new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh", year: "numeric", month: "2-digit", day: "2-digit" }).format(d) }
function Metric({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: React.ReactNode }) { return <div className="rounded-xl border border-border bg-panel p-4"><div className="flex items-center justify-between text-sm text-foreground/55"><span>{label}</span>{icon}</div><div className="mt-2 font-mono text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-foreground/45">{detail}</div></div> }

export function SignalsApp({ recommendations, events, performance, monitorReady, cronSecretReady, readError }: { recommendations: TradeRecommendation[]; events: SignalEventRow[]; performance: RecommendationPerformance; monitorReady: boolean; cronSecretReady: boolean; readError: string }) {
  const open = recommendations.filter((row) => row.status === "Open")
  const openTickers = new Set(open.map((row) => row.ticker))
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date())
  const latestWatchByTicker = new Map<string, SignalEventRow>()
  for (const row of events) {
    if (row.type !== "WATCH" || openTickers.has(row.ticker) || dateKey(row.signalTime) !== today || latestWatchByTicker.has(row.ticker)) continue
    latestWatchByTicker.set(row.ticker, row)
  }
  const candidates = [...latestWatchByTicker.values()]
  const recentEvents = events.filter((row) => row.type !== "WATCH").slice(0, 50)

  return <div className="min-h-screen bg-background text-[15px]"><TopNav/><main className="mx-auto max-w-[1600px] p-4 lg:p-6">
    <header className="flex flex-col justify-between gap-3 lg:flex-row"><div><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-brand"/><h1 className="text-2xl font-semibold">Khuyến nghị & Signal Monitor</h1></div><p className="mt-2 text-sm text-foreground/55">Notion lưu recommendation/signal. Workflow chạy 07:00, chờ opening print ATO rồi theo dõi candidate và alpha so với VNINDEX xuyên suốt phiên.</p></div><Link href="/research/scanner" className="rounded border border-border px-3 py-2 text-sm">← Daily Scanner</Link></header>
    <div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded border border-up/25 bg-up/10 px-2.5 py-1 text-up">Data · Notion</span><span className="rounded border border-border px-2.5 py-1">DNSE · {monitorReady ? 'ready' : 'missing env'}</span><span className="rounded border border-border px-2.5 py-1">Workflow 07:00 · {cronSecretReady ? 'ready' : 'missing CRON_SECRET'}</span><span className="rounded border border-border px-2.5 py-1">ATO · 09:00–09:15</span><span className="rounded border border-border px-2.5 py-1">Monitor · 5m khi có bullish candidate/open · 15m khi idle</span></div>
    {readError ? <div className="mt-3 rounded border border-down/30 bg-down/10 p-3 text-sm text-down">Không đọc được Notion: {readError}</div> : null}
    <section className="mt-4 rounded-xl border border-border bg-panel p-4"><div className="flex items-start gap-3"><Clock3 className="mt-0.5 h-4 w-4 text-brand"/><div><div className="font-semibold">Daily execution flow</div><p className="mt-1 text-sm leading-6 text-foreground/55">07:00 refresh Daily/Wyckoff context → durable sleep → ~09:15 xác nhận opening print → monitor bullish candidates mỗi 5 phút → BUY/SELL nếu rule thỏa → đọc closing print ATC ~14:45. Candidate chưa đạt BUY được lưu WATCH kèm từng gate pass/fail để audit.</p></div></div></section>

    <section className="mt-5 overflow-hidden rounded-xl border border-border bg-panel"><div className="border-b border-border px-4 py-3"><h2 className="font-semibold">Candidates đang theo dõi</h2><p className="mt-1 text-xs text-foreground/40">WATCH gần nhất trong hôm nay; hiển thị lý do reject và trạng thái từng BUY gate.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead className="bg-panel-2 text-left text-xs text-foreground/45"><tr><th className="px-4 py-3">Time</th><th className="px-4 py-3">Ticker</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Volume pace</th><th className="px-4 py-3">Reject diagnostics</th></tr></thead><tbody>{candidates.map((row)=><tr key={row.id} className="border-t border-border"><td className="px-4 py-3">{time(row.signalTime)}</td><td className="px-4 py-3"><TickerResearchLink ticker={row.ticker} className="font-mono font-bold hover:text-brand">{row.ticker}</TickerResearchLink></td><td className="px-4 py-3 font-mono">{num(row.price)}</td><td className="px-4 py-3 font-mono">{row.relVolume == null ? "—" : `${row.relVolume.toFixed(2)}x`}</td><td className="max-w-[760px] px-4 py-3 text-foreground/60">{row.rule}</td></tr>)}</tbody></table>{!candidates.length?<div className="p-5 text-sm text-foreground/45">Chưa có WATCH diagnostics trong hôm nay.</div>:null}</div></section>

    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Open" value={String(performance.open)} detail="Recommendation đang mở" icon={<Activity className="h-4 w-4"/>}/><Metric label="Closed" value={String(performance.closed)} detail="Đã có BUY/EXIT lifecycle" icon={<Target className="h-4 w-4"/>}/><Metric label="Win rate" value={performance.winRate == null ? '—' : `${performance.winRate.toFixed(1)}%`} detail={`${performance.wins}W · ${performance.losses}L · ${performance.flats}F`} icon={<Trophy className="h-4 w-4"/>}/><Metric label="Avg return" value={pct(performance.avgReturn)} detail={`VNINDEX ${pct(performance.avgVnindexReturn)}`} icon={<ChartNoAxesCombined className="h-4 w-4"/>}/><Metric label="Avg alpha" value={pct(performance.avgAlpha)} detail="vs VNINDEX holding window" icon={<ChartNoAxesCombined className="h-4 w-4"/>}/><Metric label="Payoff" value={performance.payoff == null ? '—' : `${performance.payoff.toFixed(2)}x`} detail={`Best ${pct(performance.bestReturn)} · Worst ${pct(performance.worstReturn)}`} icon={<ShieldAlert className="h-4 w-4"/>}/></section>

    <section className="mt-5 overflow-hidden rounded-xl border border-border bg-panel"><div className="border-b border-border px-4 py-3"><h2 className="font-semibold">Open recommendations</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead className="bg-panel-2 text-left text-xs text-foreground/45"><tr><th className="px-4 py-3">Ticker</th><th className="px-4 py-3">Entry</th><th className="px-4 py-3">Last</th><th className="px-4 py-3">Stop</th><th className="px-4 py-3">Target</th><th className="px-4 py-3">MFE / MAE</th><th className="px-4 py-3">Last monitor</th></tr></thead><tbody>{open.map((row)=><tr key={row.id} className="border-t border-border"><td className="px-4 py-3"><TickerResearchLink ticker={row.ticker} className="font-mono font-bold hover:text-brand">{row.ticker}</TickerResearchLink></td><td className="px-4 py-3 font-mono">{num(row.buyPrice)}</td><td className="px-4 py-3 font-mono">{num(row.lastPrice)}</td><td className="px-4 py-3 font-mono text-down">{num(row.stopPrice)}</td><td className="px-4 py-3 font-mono">{num(row.targetPrice)}</td><td className="px-4 py-3 font-mono">{pct(row.maxFavorablePct)} / {pct(row.maxAdversePct)}</td><td className="px-4 py-3">{time(row.lastMonitor)}</td></tr>)}</tbody></table>{!open.length?<div className="p-5 text-sm text-foreground/45">Chưa có recommendation đang mở.</div>:null}</div></section>

    <section className="mt-5 overflow-hidden rounded-xl border border-border bg-panel"><div className="border-b border-border px-4 py-3"><h2 className="font-semibold">Recent signal events</h2><p className="mt-1 text-xs text-foreground/40">Chỉ BUY / SELL / EXIT_FAIL; WATCH được tách riêng phía trên.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-panel-2 text-left text-xs text-foreground/45"><tr><th className="px-4 py-3">Time</th><th className="px-4 py-3">Ticker</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Rule</th><th className="px-4 py-3">Provider</th></tr></thead><tbody>{recentEvents.map((row)=><tr key={row.id} className="border-t border-border"><td className="px-4 py-3">{time(row.signalTime)}</td><td className="px-4 py-3 font-mono font-bold">{row.ticker}</td><td className="px-4 py-3">{row.type}</td><td className="px-4 py-3 font-mono">{num(row.price)}</td><td className="max-w-[520px] px-4 py-3 text-foreground/60">{row.rule}</td><td className="px-4 py-3">{row.provider}</td></tr>)}</tbody></table>{!recentEvents.length?<div className="p-5 text-sm text-foreground/45">Chưa có BUY/SELL/EXIT_FAIL event.</div>:null}</div></section>
  </main></div>
}
