begin;

create table public.market_ohlcv_provenance (
  id bigint generated by default as identity primary key,
  identity_version smallint not null default 1,
  provider text not null,
  provider_detail text not null,
  source_url text not null,
  created_at timestamptz not null default now(),
  unique (identity_version, provider, provider_detail, source_url),
  check (identity_version = 1)
);

alter table public.market_ohlcv_history
  add column provenance_id bigint null;

alter table public.market_ohlcv_history
  add constraint market_ohlcv_history_provenance_id_fkey
  foreign key (provenance_id)
  references public.market_ohlcv_provenance(id)
  on delete restrict;

alter table public.market_ohlcv_provenance enable row level security;
revoke all privileges on table public.market_ohlcv_provenance from public, anon, authenticated, service_role;
grant select, insert, update on table public.market_ohlcv_provenance to service_role;
grant usage, select on sequence public.market_ohlcv_provenance_id_seq to service_role;

create or replace function public.qeo_market_ohlcv_provenance_identity_immutable_guard()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.identity_version is distinct from old.identity_version
    or new.provider is distinct from old.provider
    or new.provider_detail is distinct from old.provider_detail
    or new.source_url is distinct from old.source_url
  then
    raise exception 'Daily OHLCV provenance identities are immutable';
  end if;
  return new;
end;
$$;

create trigger qeo_market_ohlcv_provenance_identity_immutable_guard
before update of identity_version, provider, provider_detail, source_url
on public.market_ohlcv_provenance
for each row
execute function public.qeo_market_ohlcv_provenance_identity_immutable_guard();

create or replace function public.qeo_market_ohlcv_provenance_consistency_guard()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  registry_row public.market_ohlcv_provenance%rowtype;
begin
  if new.provenance_id is null then
    return new;
  end if;

  select *
  into registry_row
  from public.market_ohlcv_provenance
  where id = new.provenance_id;

  if not found then
    raise exception 'Daily OHLCV provenance_id % does not exist', new.provenance_id;
  end if;

  if new.provider is distinct from registry_row.provider
    or new.provider_detail is distinct from registry_row.provider_detail
    or new.source_url is distinct from registry_row.source_url
  then
    raise exception 'Daily OHLCV provenance mismatch for %.% at %', new.ticker, new.timeframe, new.bar_time;
  end if;

  return new;
end;
$$;

create trigger qeo_market_ohlcv_provenance_consistency_guard
before insert or update of provenance_id, provider, provider_detail, source_url
on public.market_ohlcv_history
for each row
execute function public.qeo_market_ohlcv_provenance_consistency_guard();

revoke all on function public.qeo_market_ohlcv_provenance_identity_immutable_guard() from public, anon, authenticated;
revoke all on function public.qeo_market_ohlcv_provenance_consistency_guard() from public, anon, authenticated;

commit;