begin;

create table if not exists public.insights_stock_ratings (
  id bigint generated by default as identity primary key,
  as_of_date date not null,
  ticker text not null check (ticker ~ '^[A-Z0-9]{2,12}$'),
  sector text,
  exchange text,
  price numeric,
  price_change_pct numeric,
  composite_score numeric check (composite_score is null or composite_score between 0 and 100),
  score_4m numeric check (score_4m is null or score_4m between 0 and 100),
  canslim_score numeric check (canslim_score is null or canslim_score between 0 and 100),
  stock_rs_score numeric check (stock_rs_score is null or stock_rs_score between 0 and 100),
  sector_rs_score numeric check (sector_rs_score is null or sector_rs_score between 0 and 100),
  stock_rrg_state text,
  sector_rrg_state text,
  source text not null default 'third_party',
  source_url text,
  raw_payload jsonb not null default '{}'::jsonb check (jsonb_typeof(raw_payload) = 'object'),
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (as_of_date, ticker, source)
);

create index if not exists insights_stock_ratings_date_score_idx
  on public.insights_stock_ratings(as_of_date desc, composite_score desc, ticker);

create index if not exists insights_stock_ratings_ticker_date_idx
  on public.insights_stock_ratings(ticker, as_of_date desc);

alter table public.insights_stock_ratings enable row level security;

revoke all on public.insights_stock_ratings from anon;
revoke all on public.insights_stock_ratings from authenticated;
grant select on public.insights_stock_ratings to anon;
grant select on public.insights_stock_ratings to authenticated;

drop policy if exists insights_stock_ratings_public_read on public.insights_stock_ratings;
create policy insights_stock_ratings_public_read
on public.insights_stock_ratings
for select
to anon, authenticated
using (true);

-- Daily ingestion is intentionally service-role only. Browser roles receive no write grant.
-- The third-party fetch/cron implementation will upsert (as_of_date, ticker, source) later.

do $$
begin
  if to_regprocedure('public.qeo_touch_updated_at()') is not null then
    drop trigger if exists qeo_insights_stock_ratings_updated_at on public.insights_stock_ratings;
    create trigger qeo_insights_stock_ratings_updated_at
    before update on public.insights_stock_ratings
    for each row execute function public.qeo_touch_updated_at();
  end if;
end
$$;

commit;
