import assert from "node:assert/strict"

export const QEO232_DAILY_PROVENANCE_WRITERS = [
  "modules/market/history/ohlcv-store.ts",
  "modules/market/history/daily-integrity.ts",
  "modules/eod/no-trade-repair-step.ts",
] as const

export const QEO232_DAILY_PROVENANCE_READERS = [
  "modules/market/history/ohlcv-store.ts",
  "modules/market/history/daily-integrity.ts",
  "modules/market/chart-data/daily-authority.ts",
  "modules/market/chart-data/service.ts",
  "modules/market/chart-data/maintenance.ts",
  "modules/market/history/daily-cold-history.ts",
  "modules/market/history/ohlcv-grouped.ts",
  "modules/wyckoff/eod-ingest.ts",
] as const

function compactSql(sql: string) {
  return sql.replace(/--[^\n]*/g, " ").replace(/\s+/g, " ").trim()
}

export function assertQeo232DailyProvenanceSchema(sql: string) {
  const source = compactSql(sql)

  assert.match(source, /create table(?: if not exists)? public\.market_ohlcv_provenance\s*\(/i)
  assert.match(source, /id bigint generated by default as identity primary key/i)
  assert.match(source, /identity_version smallint not null default 1/i)
  assert.match(source, /provider text not null/i)
  assert.match(source, /provider_detail text not null/i)
  assert.match(source, /source_url text not null/i)
  assert.match(source, /check\s*\(\s*identity_version\s*=\s*1\s*\)/i)
  assert.match(
    source,
    /unique\s*\(\s*identity_version\s*,\s*provider\s*,\s*provider_detail\s*,\s*source_url\s*\)/i,
  )

  assert.match(
    source,
    /alter table public\.market_ohlcv_history[\s\S]*?add column(?: if not exists)? provenance_id bigint(?: null)?/i,
  )
  assert.match(
    source,
    /foreign key\s*\(\s*provenance_id\s*\)[\s\S]*?references public\.market_ohlcv_provenance\s*\(\s*id\s*\)[\s\S]*?on delete restrict/i,
  )

  assert.match(source, /create or replace function public\.qeo_market_ohlcv_recent_grouped/i)
  assert.match(
    source,
    /jsonb_build_array\([\s\S]*?h\.bar_time\s*,\s*h\.open\s*,\s*h\.high\s*,\s*h\.low\s*,\s*h\.close\s*,\s*h\.volume\s*,\s*h\.provider\s*,\s*h\.provider_detail\s*,\s*h\.source_url\s*,\s*h\.fetched_at[\s\S]*?\)/i,
  )

  assert.doesNotMatch(source, /provenance_id bigint not null/i)
  assert.doesNotMatch(source, /alter column provenance_id set not null/i)
  assert.doesNotMatch(source, /on delete cascade/i)

  for (const column of ["provider", "provider_detail", "source_url", "fetched_at"]) {
    assert.doesNotMatch(
      source,
      new RegExp(`drop\\s+column(?:\\s+if\\s+exists)?\\s+${column}\\b`, "i"),
    )
  }

  assert.doesNotMatch(source, /chart_ohlcv_provenance_batches/i)
  assert.doesNotMatch(source, /delete from public\.market_ohlcv_history/i)
  assert.doesNotMatch(source, /truncate(?: table)? public\.market_ohlcv_history/i)
  assert.doesNotMatch(source, /vacuum\s+full/i)
  assert.doesNotMatch(
    source,
    /create table[^;]*?\bas\s+select\b[^;]*?from public\.market_ohlcv_history/i,
  )
}
